In [4]:
import spacy
nlp = spacy.load('en_core_web_sm')
nlp(u'lion').vector

array([-0.37331197, -0.636077  ,  0.16624087, -0.4500625 ,  0.02346338,
       -0.03507689,  1.2888179 ,  0.5569869 ,  0.00782521,  0.03196311,
        0.53636825, -0.53003603, -0.5546204 ,  0.07603534, -0.6676563 ,
        0.64938223, -0.57278097, -0.42561203,  0.78977346,  0.23432143,
       -0.4744925 ,  1.4517382 , -0.6984429 ,  0.17191873,  0.57576656,
        0.8409606 ,  0.5306976 , -0.16426727, -0.31692672,  1.1624684 ,
       -0.02932239,  0.6820288 , -0.09631193,  0.4340958 , -0.7869414 ,
       -0.67758393,  0.15711513,  0.77149993, -0.42237112,  0.43566388,
       -0.48777014,  0.05853128,  0.10582243,  0.6809435 ,  0.2115672 ,
        0.31190214, -0.5367352 , -0.71792245, -0.7814528 , -0.5595007 ,
       -0.06030444, -0.235009  ,  0.14786157, -0.9114496 , -0.04370221,
        0.33902794,  1.3769817 ,  0.03151399, -0.01746303,  0.17750838,
       -0.8129017 , -0.08208682, -0.45948845, -0.25383136, -0.22368991,
        0.00536951,  0.355986  , -0.08492555, -1.2826453 , -0.31713837,
       -0.05259013,  0.72026825,  0.06919017,  0.86950725, -0.32498598,
       -0.7104281 , -0.2691805 , -0.86355877,  0.01898009,  0.47686198,
       -0.25541353, -0.32858473, -0.72884005,  0.10324007, -0.5523401 ,
        0.44613484,  0.12074314,  0.4141845 , -0.6831957 ,  0.53131336,
       -1.0593603 ,  0.40895098,  0.9865373 , -0.13632178,  0.66824126,
        0.50666654], dtype=float32)

In [5]:
doc = nlp(u"The quick brown fox jumped over the lazy dogs")
doc.vector

array([ 0.45513046, -0.14485502,  0.16430351,  0.2978505 , -0.23759753,
       -0.02327176, -0.10471906, -0.07846142,  0.2676797 , -0.01428897,
       -0.22097452,  0.6244394 , -0.05141204, -0.22487691, -0.15138212,
        0.16547152, -0.3912109 ,  0.24207221, -0.2418357 ,  0.15748262,
       -0.5027497 ,  0.01054243,  0.04287991, -0.5413457 ,  0.17790109,
       -0.40094852,  0.12196016, -0.08497206,  0.30273885,  0.14716445,
        0.14684023, -0.43884885, -0.07145125, -0.36248726, -0.21648172,
       -0.12598129,  0.17843892,  0.29266348,  0.19617234, -0.08669288,
       -0.03484626,  0.5718139 , -0.15869847, -0.20522475,  0.17272586,
       -0.2119602 ,  0.06190042,  0.3394802 ,  0.05434202,  0.10673322,
       -0.1351905 ,  0.24442452, -0.05608265,  0.07816923, -0.5617731 ,
        0.6869217 , -0.07591183,  0.23071569, -0.39543447,  0.2728924 ,
       -0.2516812 , -0.12472036, -0.24753281, -0.5796607 , -0.09872232,
       -0.3197016 ,  0.19952166, -0.14132693,  0.03925468, -0.35017896,
        0.01974586,  0.20425521,  0.08181792, -0.00778564, -0.24185371,
       -0.4220463 ,  0.11029564, -0.614316  ,  0.39858642, -0.400296  ,
       -0.27928865,  0.03041822, -0.28582293,  0.10202064, -0.11624302,
        0.3889851 ,  0.75077003, -0.31747788, -0.07403845,  0.11649389,
        0.10007934,  0.34222552,  0.59273833,  0.44912046, -0.33345807,
       -0.3255919 ], dtype=float32)

In [6]:
tokens = nlp(u'lion cat pet')
tokens

lion cat pet

In [7]:
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.7044516205787659
lion pet 0.3186751902103424
cat lion 0.7044516205787659
cat cat 1.0
cat pet 0.36159902811050415
pet lion 0.3186751902103424
pet cat 0.36159902811050415
pet pet 1.0

/tmp/ipython-input-914047137.py:3: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))

In [8]:
nlp(u'lion').similarity(nlp(u'dandelion'))

/tmp/ipython-input-1276038593.py:1: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  nlp(u'lion').similarity(nlp(u'dandelion'))

0.7058143615722656

In [9]:
tokens = nlp(u' love like here')
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

    1.0
  love 0.04361095651984215
  like -0.027747035026550293
  here 0.03770992532372475
love   0.04361095651984215
love love 1.0
love like 0.00011523594002937898
love here 0.03018038347363472
like   -0.027747035026550293
like love 0.00011523594002937898
like like 1.0
like here 0.18770897388458252
here   0.03770992532372475
here love 0.03018038347363472
here like 0.18770897388458252
here here 1.0

/tmp/ipython-input-2715115423.py:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))

In [15]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [19]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [20]:
a = 'This is a good movie'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [21]:
a= ' This was the best, most awesome movie EVER MADE!!!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [22]:
a='This was the worst film to ever disgrace the screen. '
sid.polarity_scores(a)

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [23]:
import numpy as np
import pandas as pd
df = pd.read_csv(r'/content/amazonreviews.tsv', sep='\t')
df.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [25]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [26]:
df.dropna(inplace=True)

In [28]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [30]:
blanks = []
for i,lb,rv in df.itertuples():
  if type(rv) == str:
    if rv.isspace():
      blanks.append(i)
df.drop(blanks, inplace = True)
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [31]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['label']

'pos'

In [32]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))
df.head()

,label,review,scores
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co..."
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co..."
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com..."
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com..."
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp..."

In [33]:
df['compound'] = df['scores'].apply(lambda score_dict: score_dict['compound'])
df.head()

,label,review,scores,compound
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781

In [35]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['scores']

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [36]:
df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
df.head()

,label,review,scores,compound,comp_score
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454,pos
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957,pos
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858,pos
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814,pos
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781,pos

In [37]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(df['label'],df['comp_score'])

0.7098

In [39]:
print(confusion_matrix(df['label'],df['comp_score']))

[[2630 2467]
 [ 435 4468]]

In [41]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000

In [ ]:
--